env_files:
  github_token: ./.env
archives:
- format: binary
build:
  binary: frogdb
  ignore:
    - goarch: "386"
dockers:
  - image_templates:
    - "sergeycrisp/frogdb:{{ .Tag }}"
    - "sergeycrisp/frogdb:latest"