env_files:
  github_token: ./.env
archives:
- format: binary
build:
  binary: frogdb
  ignore:
    - goarch: "386"
dockers:
  - image_templates:
    - sergeycrisp/frogdb
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"